version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: pms_db
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./infra/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - pms-network

volumes:
  pg-data:

networks:
  pms-network:
    driver: bridge
